version: '3'
services:
  react-docker:
    container_name: react-docker
    build:
      context: ./react-docker
    ports:
      - "3000:3000"
    volumes:
       - ./react-docker:/usr/src/app/react-docker
       - ./react-docker/node_modules/:/usr/src/app/react-docker/node_modules